/**
 * local-harness.mts — minimal HTTP server wrapping api/mcp.ts for local testing.
 *
 * Loads env from ../../.env.local (vercel env pull output), then serves the
 * fetchHandler on http://localhost:4747/mcp so contract-test.py can run against it.
 *
 * Usage (from hosted-server/vercel/):
 *   node_modules/.bin/tsx local-harness.mts
 */
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── load env from ../.env.local (production KV creds from vercel env pull) ─
// The file lives at hosted-server/.env.local (generated by `vercel env pull` from
// hosted-server/), which is one level above vercel/.
const envFile = resolve(__dirname, "../.env.local");
try {
  const raw = readFileSync(envFile, "utf8");
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx < 0) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    let val = trimmed.slice(eqIdx + 1).trim();
    // Strip surrounding quotes (single or double)
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    process.env[key] = val;
  }
  console.log("[harness] loaded .env.local from", envFile);
} catch (e) {
  console.warn("[harness] could not load .env.local:", e);
}

// Mark as Vercel environment so isHostedEnvironment() → true
process.env.VERCEL = "1";

// ── import handler AFTER env is loaded ────────────────────────────────────────
// The default export of mcp.ts is a Node.js-style handler: (req, res) => void.
const { default: handler } = await import("./api/mcp.js");

const PORT = 4747;

// mcp.ts default export is already the Node adapter — pass req/res directly.
createServer(async (req, res) => {
  try {
    await handler(req, res);
  } catch (e) {
    console.error("[harness] handler error:", e);
    if (!res.headersSent) {
      res.statusCode = 500;
      res.end(JSON.stringify({ error: String(e) }));
    }
  }
}).listen(PORT, () => {
  console.log(`[harness] listening on http://localhost:${PORT}`);
  console.log(`[harness] NOVADA_SERVER_VERSION = ${process.env.NOVADA_SERVER_VERSION}`);
});
